version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5002:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - SESSION_SECRET=secret
    command: npm run dev
