version: "3"
services:
  node-app:
    build: .
    environment:
      - PORT=3000
      - MONGO_USER=root
      - MONGO_PASSWORD=password
      - MONGO_PORT=27017
      - MONGO_IP=mongo
    depends_on:
      - mongo
    # env_file:
    #   - ./.env
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
    ports:
      - "27018:27017"
  redis:
    image: redis

volumes:
  mongo-db:
